application.name: m1

dataSource:
  jdbc:
    url: jdbc:hsqldb:mem:test?shutdown=true
    driver_class: org.hsqldb.jdbcDriver
    max_pool_size: 30
    user: SA
    password: ""

server:
  port: 8080
